[application]
basedir = "data"

[application.log]
path = "."
prefix = "log"
interval = 5000

[application.rebalance]
interval = 10
loglevel = 1

[application.option]
vectorization = "vector"

[[diagnostic]]
name = "history"
path = "."
prefix = "history"
interval = 500

[[diagnostic]]
name = "field"
path = "."
prefix = "field"
interval = 500

[[diagnostic]]
name = "particle"
path = "."
prefix = "particle"
fraction = 1.0
interval = 5000

[parameter]
Nx = 2
Ny = 1024
Nz = 1
Cx = 1
Cy = 64
Cz = 1
Ns = 3
cc = 1.0
wp = 1.0
delt = 0.025
delh = 0.05
nppc = 64
mime = 400
ush = 0.25
theta = 90.0
phi = 0.0
sigma = 0.01
alpha = 0.5
betae = 0.5
betai = 5.0
betar = 5.0
